CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	email TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL
);

CREATE TABLE sessions (
   id SERIAL PRIMARY KEY,
   token TEXT NOT NULL UNIQUE,
   "userId" INTEGER NOT NULL REFERENCES users(id)
);

CREATE TABLE "shortenUrls" (
	id SERIAL NOT NULL PRIMARY KEY,
	"longUrl" TEXT NOT NULL UNIQUE,
	"shortUrl" TEXT NOT NULL UNIQUE,
	"userId" INTEGER NOT NULL REFERENCES users(id)
);